# Generated by Django 5.2.8 on 2025-11-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
